version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: guessheads-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080
    networks:
      - guessheads-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: guessheads-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - guessheads-network

networks:
  guessheads-network:
    name: guessheads-network
    driver: bridge
